// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzwzhgkfhwbszuwkbhxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6d3poZ2tmaHdic3p1d2tiaHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTc3MzYsImV4cCI6MjA2Njk3MzczNn0.jmtbh8a7ZkwZaSakS5jZPtwWCRhSLY5-2rp6_-KkQ9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});